//Function or block scoped

//var - function scoped

// for(var i = 0;i<5;i++)
// {
//     console.log(i);
// }

// console.log(i);

//let - block scoped
// for(let i = 0;i<5;i++)
// {
//     console.log(i);
// }

// console.log(i);


//const- block scoped

//  for(const i = 0;i<5;i++)
// {
//     console.log(i);
// }

// console.log(i);

// -----------------------------------------------------
//redeclaring 

//var can be redeclared
// var cat = "meow"
// var cat = "pssss"

//let cannot be redeclared
// let dog = "boww"
// let dog = "huh"

// const cannot be redeclared
// const lion = "roar"
// const lion = "rooor"

//-----------------------------------------------------------

//redefining
//var can be redefined
// var dog = "boww"
// dog   = "voww"

//let can be redefined
// let cat = "meow"
// cat = "psss"

//const cannot be redefined
const lion = "roar"
lion = "roar"